# CalDav Testing farm 
#
# Access via "http://localhost:80" (or "http://$(docker-machine ip):80" if using docker-machine)
#
# Some services like bedework and mysql are there for future developements
# 
# How to run it
# #############
#
# Read README.md , but is simple like
#
# docker-compose up
#
# ENJOY!!!!
#
# ChangeLog:
#
# 0.0.1 Owncloud for now are preprovisioned with admin:merproject and sqlite backend
#
#
version: '2'

services:

  owncloud_9.1:
    image: owncloud:9.1
    volumes:
    - ./conf/owncloud/9.1/config.php:/var/www/html/config/config.php
#   ports:
#   - 18091:80

  owncloud_9.0:
    image: owncloud:9.0
    volumes:
    - ./conf/owncloud/9.0/config.php:/var/www/html/config/config.php
#   ports:
#   - 18090:80
  
  owncloud_8.2:
    image: owncloud:8.2
    volumes:
    - ./conf/owncloud/8.2/config.php:/var/www/html/config/config.php
#    ports:
#      - 18082:80
 
  owncloud_8.1:
    image: owncloud:8.1
    volumes:
    - ./conf/owncloud/8.1/config.php:/var/www/html/config/config.php
#    ports:
#      - 18081:80
  
  owncloud_8.0:
    image: owncloud:8.0
    volumes:
    - ./conf/owncloud/8.0/config.php:/var/www/html/config/config.php
#    ports:
#      - 18080:80
  
#  bedework:
#    image: ioggstream/bedework
#    ports:
#      - 13103:8000
  
#  mysql:
#    image: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: merproject

  nginx:
    volumes:
    - ./conf/nginx/reverseproxy.conf:/etc/nginx/conf.d/reverseproxy.conf
    image: nginx
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=tstsrv.in.merproject.org
    - NGINX_PORT=80
    command: /bin/bash -c "nginx -g 'daemon off;'"
