# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"

version: '2'

services:

  owncloud_9.1:
    image: owncloud:9.1
    ports:
      - 18091:80

  owncloud_9.0:
    image: owncloud:9.0
    ports:
      - 18090:80
  
  owncloud_8.2:
    image: owncloud:8.2
    ports:
      - 18082:80
 
  owncloud_8.1:
    image: owncloud:8.1
    ports:
      - 18081:80
  
  owncloud_8.0:
    image: owncloud:8.0
    ports:
      - 18080:80
  
  bedework:
    image: ioggstream/bedework
    ports:
      - 13103:8000
  
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: merproject
